export const DEFAULT_ACTION = 'DEFAULT_ACTION';

export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR';

//#region Reset doable for this state
export const RESET_COURSE_DOABLES = 'RESET_COURSE_DOABLES';
export const TOGGLE_COURSE_BOOLEANABLE_STATE = 'TOGGLE_COURSE_BOOLEANABLE_STATE';
export const TOGGLE_COURSE_ERRABLE_STATE = 'TOGGLE_COURSE_ERRABLE_STATE';
export const TOGGLE_COURSE_SUCCESSIBLE_STATE = 'TOGGLE_COURSE_SUCCESSIBLE_STATE';
//#endregion

/* new-constant-export-goes-here */